### ISSUE TITLE
 cannot load '@rules_rust//proto:repositories.bzl': no such file

### ISSUE THREAD

**Issue by Zemnmez** [Calsign/gazelle_rust#2]
Thank you for your hard work on this project. I'm really excited to use these rules.

I think the current code is a little out of sync with upstream rules_rust:

```
ERROR: Error computing the main repository mapping: at /private/var/tmp/_bazel_tshadwell/15310e5df52295849af33b570a7d9e6c/external/gazelle_rust/deps2.bzl:7:6: cannot load '@rules_rust//proto:repositories.bzl': no such file
```

I think the file you're looking for is now in https://github.com/bazelbuild/rules_rust/blob/main/proto/protobuf/repositories.bzl

**Comment by Calsign** [comment]
Good call. I upgraded rules_rust with https://github.com/Calsign/gazelle_rust/commit/1595d075026901ac516e9532218a87e07bcb0163 and fixed the issue. Closing now, feel free to reopen if you encounter other related issues.

**Comment by Zemnmez** [comment]
Thank you!
