### ISSUE TITLE
Make this gazelle plugin more discoverable :)

### ISSUE THREAD

**Issue by kolloch** [Calsign/gazelle_rust#4]
I heard about this plugin only in the Slack Bazel chat:

> Daniel Wagner-Hall
>  [2023-08-25](https://bazelbuild.slack.com/archives/CSV56UT0F/p1692898330675279?thread_ts=1692892135.667979&cid=CSV56UT0F)
> There is https://github.com/Calsign/gazelle_rust but IIRC it just works from .rs files not Cargo.toml

It is also weirdly ungoogleable for me with "gazelle rust bazel".

It would be awesome if you create a PR to include it here:

https://github.com/bazelbuild/bazel-gazelle#supported-languages

(I am also happy to do it for you)

**Comment by Calsign** [comment]
> It would be awesome if you create a PR to include it here:

Good call! Opened a PR: https://github.com/bazelbuild/bazel-gazelle/pull/1620

> It is also weirdly ungoogleable for me with "gazelle rust bazel".

Yeah I'm sure what it takes to change that. Maybe more people using it :slightly_smiling_face:
