### ISSUE TITLE
Gazelle Rust doesnt work with new rules_rust

### ISSUE THREAD

**Issue by ericmcbride** [Calsign/gazelle_rust#7]
```
error[E0603]: module `context` is private
  --> external/gazelle_rust/rust_parser/lockfile_crates.rs:23:31
   |
23 |     let context: cargo_bazel::context::Context = match serde_json::from_str(&lockfile_str) {
   |                               ^^^^^^^ private module
   |
note: the module `context` is defined here
  --> external/rules_rust/crate_universe/src/lib.rs:6:1

error[E0603]: module `utils` is private
   --> external/gazelle_rust/rust_parser/lockfile_crates.rs:135:43
    |
135 |         package.crate_name = cargo_bazel::utils::sanitize_module_name(&package.name);
    |                                           ^^^^^ private module
    |
note: the module `utils` is defined here
   --> external/rules_rust/crate_universe/src/lib.rs:11:1

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0603`.
Aspect @rules_rust//rust/private:clippy.bzl%rust_clippy_aspect of //:gazelle-rust up-to-date (nothing to build)
INFO: Elapsed time: 1.777s, Critical Path: 0.09s
INFO: 2 processes: 2 internal.
```

We are wanting to switch to gazelle to generate our rust files for us since we have had great success with go's gazelle.  Currently we are seeing these errors while using this version of rules rust in our WORKSPACe file
```
http_archive(
    name = "rules_rust",
    sha256 = "6357de5982dd32526e02278221bb8d6aa45717ba9bbacf43686b130aa2c72e1e",
    urls = ["https://github.com/bazelbuild/rules_rust/releases/download/0.30.0/rules_rust-v0.30.0.tar.gz"],
)
```

**Comment by Calsign** [comment]
This doesn't look like a change in rules_rust, rather I think you are just missing the patch. From the README:

> gazelle_rust currently requires a patch to rules_rust in order to expose the logic needed to parse crate_universe lockfiles. This is required even if you don't use crate_universe. gazelle_rust provides patches that work both with and without the -p1 flag, and example/WORKSPACE shows how to apply the patch to rules_rust.

So please see the example: https://github.com/Calsign/gazelle_rust/blob/main/example/WORKSPACE#L14

For context, this needs to be fixed by upstreaming a change to rules_rust. I have an [open issue](https://github.com/bazelbuild/rules_rust/issues/1725), but I haven't gotten around to actually making the change yet.
